# Generated by Django 5.2 on 2025-05-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('trainer', 'Entrenador'), ('athlete', 'Deportista'), ('guest', 'Invitado')], default='guest', max_length=20),
        ),
    ]
