# Generated by Django 5.2 on 2025-05-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WgerExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wger_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('muscle_group', models.CharField(blank=True, max_length=255)),
                ('difficulty', models.CharField(blank=True, max_length=50)),
                ('equipment', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
